#!/usr/bin/python
# -*- coding: utf-8 -*-

dictionary = dict((
    ('UUU', 'F'),
    ('CUU', 'L'),
    ('AUU', 'I'),
    ('GUU', 'V'),
    ('UUC', 'F'),
    ('CUC', 'L'),
    ('AUC', 'I'),
    ('GUC', 'V'),
    ('UUA', 'L'),
    ('CUA', 'L'),
    ('AUA', 'I'),
    ('GUA', 'V'),
    ('UUG', 'L'),
    ('CUG', 'L'),
    ('AUG', 'M'),
    ('GUG', 'V'),
    ('UCU', 'S'),
    ('CCU', 'P'),
    ('ACU', 'T'),
    ('GCU', 'A'),
    ('UCC', 'S'),
    ('CCC', 'P'),
    ('ACC', 'T'),
    ('GCC', 'A'),
    ('UCA', 'S'),
    ('CCA', 'P'),
    ('ACA', 'T'),
    ('GCA', 'A'),
    ('UCG', 'S'),
    ('CCG', 'P'),
    ('ACG', 'T'),
    ('GCG', 'A'),
    ('UAU', 'Y'),
    ('CAU', 'H'),
    ('AAU', 'N'),
    ('GAU', 'D'),
    ('UAC', 'Y'),
    ('CAC', 'H'),
    ('AAC', 'N'),
    ('GAC', 'D'),
    ('UAA', ''),
    ('CAA', 'Q'),
    ('AAA', 'K'),
    ('GAA', 'E'),
    ('UAG', ''),
    ('CAG', 'Q'),
    ('AAG', 'K'),
    ('GAG', 'E'),
    ('UGU', 'C'),
    ('CGU', 'R'),
    ('AGU', 'S'),
    ('GGU', 'G'),
    ('UGC', 'C'),
    ('CGC', 'R'),
    ('AGC', 'S'),
    ('GGC', 'G'),
    ('UGA', ''),
    ('CGA', 'R'),
    ('AGA', 'R'),
    ('GGA', 'G'),
    ('UGG', 'W'),
    ('CGG', 'R'),
    ('AGG', 'R'),
    ('GGG', 'G'),
    ))
with open('rosalind_splc.txt') as f:
    s = f.readline().strip()
    sres = s
    for dl in filter(None, map(str.strip, f.readlines())):
        s1 = s.replace(dl, '#' * len(dl))
        sres = map(lambda x: ('#' if x[0] == '#' or x[1] == '#' else x[0]), zip(s1, sres))
    s = ''.join(sres).replace('T', 'U').replace('#', '')
print ''.join(dictionary[s[3 * i:3 * i + 3]] for i in xrange(len(s) / 3))
